[project]
name = "agent-service"
version = "0.1.0"
description = "Agent service for handling OpenAI agent logic"
requires-python = ">=3.13,<3.14"

[tool.pdm]
distribution = false

[project.dependencies]
annotated-types = "0.7.0"
anyio = "4.9.0"
certifi = "2025.1.31"
charset-normalizer = "3.4.1"
click = "8.1.8"
colorama = "0.4.6"
distro = "1.9.0"
fastapi = "0.115.12"
griffe = "1.7.1"
h11 = "0.14.0"
httpcore = "1.0.7"
httpx = "0.28.1"
httpx-sse = "0.4.0"
idna = "3.10"
jiter = "0.9.0"
mcp = "1.6.0"
openai = "1.69.0"
openai-agents = { git = "https://github.com/openai/openai-agents-python.git", rev = "main" }
pydantic = "2.11.1"
pydantic-core = "2.33.0"
pydantic-settings = "2.8.1"
python-dotenv = "1.1.0"
requests = "2.32.3"
sniffio = "1.3.1"
sse-starlette = "2.2.1"
starlette = "0.46.1"
tqdm = "4.67.1"
types-requests = "2.32.0.20250328"
typing-extensions = "4.13.0"
typing-inspection = "0.4.0"
urllib3 = "2.3.0"
uvicorn = "0.34.0"
